name: cyclop
description: a flutter colorpicker with an eyedropper
version: 0.2.1
homepage: https://github.com/rxlabz/cyclop

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^2.1.1
  quiver: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/grid.png
