name: cyclop
description: An experimental flutter colorpicker with an optional eyedropper tool ( Material colors swatches, AHSL, ARGB and custom swatches library )
version: 0.6.2
homepage: https://github.com/rxlabz/cyclop

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.15
  quiver: ^3.2.1
  basics: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/grid.png
